spring:
  application:
    name: @project.name@

  security:
    user:
      name: user
      password: pw
      roles:
        - "read"
        - "write"

jwt:
  private: classpath:app.key
  public: classpath:app.pub